config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :tweets, only:[:create, :destroy, :new]
  end

  root "users#index"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    belongs_to :user
    validates :tweet, presence: true
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :tweets, dependent: :destroy
    validates :name, presence: true,
                     uniqueness: true,
                     length: {
                        minimum: 3,
                        maximum: 20
                     },
                     format: {
                        with: /\A[a-zA-Z0-9]+\Z/
                     }

    def image
        if img_url.blank?
            ""
        else
            img_url
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @user = User.find(params[:user_id])
    @tweets = @user.tweets
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @user = User.find(params[:user_id])
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @user = User.find(params[:user_id])
    if @user.save
      @tweet = @user.tweets.create(tweet_params)
      redirect_to user_path(@user)
    else
      flash[:error] = 'Erreur lors de la création du tweet'
      redirect_to user_path(@user)
    end
  end

  # PATCH/PU@tweets
  # PATCH/PU@tweetson
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1@tweets
  # DELETE /tweets/1.json@tweets
  def destroy
    @user = User.find(params[:user_id])
    @tweet = @user.tweets.find(params[:id])
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user), notice: 'Le tweet a bien été supprimer !' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @tweet = Tweet.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :img_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar has-background-danger has-text-white" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="">
        <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item has-text-white" href="/users">
          Accueil
        </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <a class="button is-primary" href="http://www.google.fr">
              <strong>Internet</strong>
            </a>
          </div>
        </div>
      </div>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweet</h1>
				<%= render 'form', tweet: @tweet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', user_tweet_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> l'utilisateur ne peut pas être créé:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card" style="width:30%; margin: 0 auto; padding:20px;">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <table style="width:100%">
              <tr>
                <td style="padding: 5px;"><label>Nom :</label></td>
                <td style="padding: 5px;"><%= f.text_field :name %></td>
              </tr>
              <tr>
                <td><label>Avatar :</label></td>
                <td><%= f.text_area :img_url %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      <%= f.submit %>
    </div>

<% end %>

app/views/users/edit.html.erb
<div style="margin:auto; text-align:center;">
  <br>

  <h1 class="title" style="padding-left:20px;">Modifier utilisateur</h1>

<%= render 'form' %>

<br><br>
<b><%= link_to '← Retour', users_path, :class => "button is-primary"%></b>
<b><%= link_to 'Détails', @user, :class => "button is-primary" %></b>

</div>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <article class='message is-success'><div class='message-body'><%= flash[:notice] %></div></article>
<% end %>

<br>

<nav class="level" style="padding-right:20px; padding-left:20px;">
  <div class="level-left">
  </div>
  <div class="level-right">
    <div class="level-item">
      <div class="buttons" >
        <a href="<%= new_user_path %>" class="button is-primary">
          <strong>Nouvelle Utilisateur</strong>
        </a>
      </div>
    </div>
  </div>
</nav>


<h1 class="title" style="padding-left:20px;">Liste des utilisateurs</h1>

<div class="columns is-multiline is-mobile" style="padding-right:20px; padding-left:20px;">
  <% @users.each do |user| %>
  <div class="column is-half-mobile is-one-third-tablet is-one-third-desktop is-one-third-widescreen is-one-quarter-fullhd">
  <div class="card">
     <a href="<%= user_path(user) %>">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <img src="<%= user.img_url %>" alt="Avatar">
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= user.name %></p>
            <p class="subtitle is-6">@<%= user.name %></p>
          </div>
        </div>
      </div>
     </a>
      <footer class="card-footer">
        <a href="<%= edit_user_path(user) %>" class="card-footer-item">Modifier</a>
        <%= link_to 'Supprimer', user_path(user), method: :delete, data: { confirm: 'Etes-vous sur de vouloir le supprimer ?' }, :class => "card-footer-item" %>
      </footer>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div style="margin:auto; text-align:center;">

  <br>
  <h1 class="title" style="padding-left:20px;">Nouvelle utilisateur</h1>

  <%= render 'form' %>

  <br><br>
  <b><%= link_to '← Retour', users_path, :class => "button is-primary"%></b>


</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <br>
  <article class='message is-success'><div class='message-body'><%= flash[:notice] %></div></article>
<% end %>

<div style="margin:auto; text-align:center;">

  <br>
  <h1 class="title" style="padding-left:20px;">Détails utilisateur</h1>

  <div class="card" style="width:60%; margin: 0 auto; padding:20px;">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-128x128">
              <img src="<%= @user.img_url %>" alt="Avatar">
          </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%= @user.name %></p>
            <p class="subtitle is-6">@<%= @user.name %></p>
        </div>
      </div>
          <div class="card">
            <div class="card-content">
              <div class="content">

                <%= form_for @tweet, url: user_tweets_path(@user) do |f| %>
                  <% if flash[:error] %>
                    <article class='message is-danger'><div class='message-body'><%= flash[:error] %></div></article>
                  <% end %>
                    <div class="field">
                      <div class="control">
                        <%= f.label :tweet %><br>
                        <%= f.text_area :tweet, :class => "textarea" %>
                      </div>
                    </div>
                    <%= f.submit "Tweeter", class: "button is-primary" %>
                <% end %>
              </div>
            </div>
          </div>

          <% @user.tweets.each do | tweet | %>
            <div class="card" style="border : solid 1px black;">
              <div class="card-content">
                <div class="content"><p><%= tweet.tweet %>
                  <br/>
                  <%= l(tweet.created_at, format: :long)%>
                </div>
              </div>
              <footer class="card-footer">
                <%= link_to 'Supprimer', user_tweet_path(id: tweet.id, user_id: @user.id), method: :delete, data: { confirm: 'Etes-vous sur de vouloir le supprimer ?' }, :class => "card-footer-item" %>
              </footer>
            </div>
            <% end %>
      </div>
        
  </div>

  <br><br>
  <b><%= link_to '← Retour', users_path, :class => "button is-primary"%></b>
  <b><%= link_to 'Modifier', edit_user_path(@user), :class => "button is-primary" %></b>
</div>

<%= link_to "Nouveau tweet", new_user_tweet_path(@user) %>